tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osgeo/osgeo4mac"
brew "openjdk"
brew "gcc", link: false
brew "open-mpi"
brew "arpack"
brew "armadillo"
brew "sqlite"
brew "python@3.8"
brew "cairo"
brew "openldap"
brew "curl"
brew "geos"
brew "proj"
brew "netcdf", link: false
brew "numpy"
brew "gdal"
brew "git"
brew "htop"
brew "hugo"
brew "jasper"
brew "jq"
brew "llvm"
brew "mackup"
brew "mas"
brew "node"
brew "pkg-config"
brew "osgeo/osgeo4mac/osgeo-postgresql"
brew "postgresql", link: false
brew "protobuf"
brew "postgis"
brew "r", link: false
brew "udunits"
brew "v8"
brew "wget"
brew "osgeo/osgeo4mac/osgeo-proj"
brew "osgeo/osgeo4mac/osgeo-libspatialite"
brew "osgeo/osgeo4mac/osgeo-netcdf"
brew "osgeo/osgeo4mac/osgeo-gdal"
cask "adobe-acrobat-reader"
cask "atom"
cask "dropbox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "java"
cask "mactex"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "r"
cask "rstudio"
cask "slack"
cask "spotify"
cask "suspicious-package"
cask "the-unarchiver"
cask "vlc"
cask "webpquicklook"
cask "xquartz"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
